### ISSUE TITLE
Can you support the latest 5k ~? thank you.

### ISSUE THREAD

**Issue by carryrs2** [yo1995/Daily_GUI_Tools#7]
I can't find any useful software working on my latest 5k.

**Comment by yo1995** [comment]
> I can't find any useful software working on my latest 5k.

Hi, could you provide more details, e.g. model #, vendor_id, product_id etc.?

Currently the tool work on my 27MD5K and 1803. Maybe we can figure out the compatibility issue together.

**Comment by abulgatz** [comment]
@yo1995 I'm not the original bug submitter, but I have the same problem.

Log is filled with `Not the correct product id`.

LG model: `27MD5KL-B`

I do not see the standard VID and PID in device manager under the "Monitors" section. Am I looking in the wrong place?

From Device manager (listed as Generic PnP Monitor)

* Device instance path: `DISPLAY\GSM5B74\4&3926DF73&0&UID224795`
* Hardware Ids: `MONITOR\GSM5B74`
* Compatible Ids: `PNP09FF`

And thanks for the software!

**Comment by yo1995** [comment]
> @yo1995 I'm not the original bug submitter, but I have the same problem.
> 
> Log is filled with `Not the correct product id`.
> 
> LG model: `27MD5KL-B`
> 
> I do not see the standard VID and PID in device manager under the "Monitors" section. Am I looking in the wrong place?
> 
> From Device manager (listed as Generic PnP Monitor)
> 
> * Device instance path: `DISPLAY\GSM5B74\4&3926DF73&0&UID224795`
> * Hardware Ids: `MONITOR\GSM5B74`
> * Compatible Ids: `PNP09FF`
> 
> And thanks for the software!

Thanks for reporting in. I'll take a look tomorrow. 😃

**Comment by abulgatz** [comment]
Thanks! Let me know if you need any more information.

**Comment by yo1995** [comment]
sorry for the delay - I'm experiencing some busy moments these weeks, as Chinese New Year is coming 😅 Nevertheless I'll try my best to look into this issue by the end of this week.

**Comment by yo1995** [comment]
> @yo1995 I'm not the original bug submitter, but I have the same problem.
> 
> Log is filled with `Not the correct product id`.
> 
> LG model: `27MD5KL-B`
> 
> I do not see the standard VID and PID in device manager under the "Monitors" section. Am I looking in the wrong place?
> 
> From Device manager (listed as Generic PnP Monitor)
> 
> * Device instance path: `DISPLAY\GSM5B74\4&3926DF73&0&UID224795`
> * Hardware Ids: `MONITOR\GSM5B74`
> * Compatible Ids: `PNP09FF`
> 
> And thanks for the software!

Hi, sorry for the delayed response. Could you please look up the UID PID under your USB device? Something like in this link: https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Compatibility_Peripherals/How_do_I_check_the_PID_VID_of_my_USB_device (Assuming you are using the Type-C port to connect to it)

Thanks! Maybe I should @abulgatz here.

---

At the meantime, I plan to extract the configuration parameters into a separate text file, so that later device ids can be added to the conf without recompiling the program. If this happens before your response, you can try it on your own to add that to the conf. Current way of using conf file is a bit not intuitive. See below.

1. Download the released folder with all 3 files: `.exe`, `.ini` and `.dll`.
2. Don't change the file names for `.ini` and `.dll` - I've hard coded those in the src... 😓 
3. Enter the PID you found for the monitor to the `.ini` file by replacing the sample line.
4. Try to see if the program can adjust brightness now.

Again, it is a temporary mitigation. I don't like coding in C++ because of lacking of basic components such as serialization stuff... If it works, I'll improve later. If not, I'll just include the latest PID into the src and recompile a new version of executable.

**Comment by yo1995** [comment]
Also referring to #5 , same problem. might solve with a separate conf file for future compatibility 

(I can hardly believe neither Apple nor LG issue an official solution to this problem after 3 years... Just port bootcamp drivers to Windows should be fine! 🤔 )

**Comment by yo1995** [comment]
Also it would be great if I can access a latest version 5K and look into its ambient light sensor someday...

**Comment by yo1995** [comment]
also check in with @carryrs2 again if you can provide the PID for the device.

**Comment by carryrs2** [comment]
Sorry for the delay. I use Gigabyte GC TITAN RIDGE linking to my lastest version 5k.
And I look your giving methods to check VID&PID (win10): Go to Control Panel > Device Manager and find your desired USB device.
I found that my 5k USB device shows **Unknown USB Device (Port Reset Failed)**
Although there are **USB\VID_0000&PID_0001\a&259967d1&0&2**, I think it might be a wrong code.
By the way, my PC is working under the AMD 3900X and the X570 motherboard, and this board doesn't have Thunderbolt TB_Header port. So sad :( but I feel so lucky because the 5k monitor can work on my PC.

**Comment by carryrs2** [comment]
保重身体，春节快乐- -#

**Comment by carryrs2** [comment]
And I have to say that Apple have released the bootcamp driver 6.1.10 that can help LG 4K/5k devices work on win10 PC. Maybe I need this driver to fix my USB bugs.
Unfortunately, I still cannot find any download links for bootcamp 6.1.10.

**Comment by yo1995** [comment]
> And I have to say that Apple have released the bootcamp driver 6.1.10 that can help LG 4K/5k devices work on win10 PC. Maybe I need this driver to fix my USB bugs.
> Unfortunately, I still cannot find any download links for bootcamp 6.1.10.

Hmm, I don't use bootcamp, but as far as my research goes, Apple does not make it available for normal Windows instances. One can only use the Apple bootcamp assistant through a bootcamp installation... 🤔

**Comment by yo1995** [comment]
> 保重身体，春节快乐- -#

谢谢 😷 春节快乐

实在不行准备改一下写法，想办法用其他标识来判断设备是不是5K……

**Comment by yo1995** [comment]
Refer to #8 as I'll stop supporting this tool due to my lost of access to the 5K monitor. 😢
